name: build

on:
  push:
#    branches:
#      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # see https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: jitolabs/jito-shredstream-proxy:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Copy artifact from container
        run: |
          docker run --rm --entrypoint cat jitolabs/jito-shredstream-proxy /app/jito-shredstream-proxy > ./jito-shredstream-proxy
          ls -lh .
          file ./jito-shredstream-proxy

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: ./jito-shredstream-proxy
#      - name: Upload
#      - uses: actions/upload-artifact@v3
#        with:
#          name: "jito-shredstream-proxy-linux-x86_64"
#          path: target/release/jito-shredstream-proxy
