name: build

on:
  push
#  push:
#    branches:
#      - master
#    tags:
#      - 'v*'
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # see https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: user/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/jito-shredstream-proxy
#      - name: Upload
#      - uses: actions/upload-artifact@v3
#        with:
#          name: "jito-shredstream-proxy-linux-x86_64"
#          path: target/release/jito-shredstream-proxy
