name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04-16c-64g
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Sanity Check
        run: |
          cat /proc/cpuinfo

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          caller-workflow-name: test

      - name: Install cargo sort
        run: |
          cargo install cargo-sort

      - name: Cargo sort
        run: cargo sort --workspace --check

      - name: Clippy check
        run: cargo clippy --all-features --all-targets --tests -- -D warnings

      - name: Fast build
        run: cargo build --release

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # see https://docs.docker.com/build/ci/github-actions/cache/#cache-backend-api
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      # NOTE: this step is slow
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: jitolabs/jito-shredstream-proxy:${{github.sha}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64,linux/amd64,linux/x86_64
