name: test

on:
  push

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq -y install libssl-dev pkg-config curl git clang


      - name: Check sanity
        run: ls -l /usr/bin

      - name: Check Rust
        run: rustc --version

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Test
        run: cargo test --all-features --locked

