name: test

on: push

jobs:
  test:
    runs-on: big-runner-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          caller-workflow-name: test

      - name: Run tests
        run: cargo test --all-features --locked

